# Generated by Django 5.2.4 on 2025-07-22 00:56
# Caminho relativo ao projeto: src/wa_fin_ctrl/apps/core/migrations/0001_initial.py
# Migração inicial para criação dos modelos Processamento, EntradaFinanceira e ArquivoProcessado

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Processamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("incremental", "Processamento Incremental"),
                            ("force", "Processamento Forçado"),
                            ("backup", "Processamento com Backup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("iniciado", "Iniciado"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="iniciado",
                        max_length=20,
                    ),
                ),
                (
                    "data_hora_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_hora_fim", models.DateTimeField(blank=True, null=True)),
                ("arquivos_processados", models.IntegerField(default=0)),
                ("arquivos_erro", models.IntegerField(default=0)),
                ("mensagem", models.TextField(blank=True)),
                ("erro", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Processamento",
                "verbose_name_plural": "Processamentos",
                "ordering": ["-data_hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="EntradaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=500)),
                (
                    "classificacao",
                    models.CharField(
                        choices=[
                            ("receita", "Receita"),
                            ("despesa", "Despesa"),
                            ("transferência", "Transferência"),
                            ("pagamento", "Pagamento"),
                            ("recebimento", "Recebimento"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("arquivo_origem", models.CharField(blank=True, max_length=255)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_modificacao", models.DateTimeField(auto_now=True)),
                ("desconsiderada", models.BooleanField(default=False)),
                (
                    "processamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.processamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada Financeira",
                "verbose_name_plural": "Entradas Financeiras",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="ArquivoProcessado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_arquivo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagem", "Imagem"),
                            ("pdf", "PDF"),
                            ("zip", "Arquivo ZIP"),
                            ("outro", "Outro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tamanho", models.BigIntegerField()),
                (
                    "data_upload",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_processamento", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pendente", max_length=20)),
                ("erro", models.TextField(blank=True)),
                (
                    "processamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.processamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo Processado",
                "verbose_name_plural": "Arquivos Processados",
                "ordering": ["-data_upload"],
            },
        ),
    ]
