# Generated by Django 5.2.4 on 2025-07-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrecaoHistorico",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("execution", models.DateTimeField(auto_now_add=True)),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("fix", "Correção de Entrada"),
                            ("dismiss", "Marcar como Desconsiderada"),
                            ("rotate", "Rotação de Imagem"),
                            ("ia", "Reprocessamento com IA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_hora_entrada", models.DateTimeField()),
                ("valor_original", models.CharField(blank=True, max_length=20)),
                ("valor_novo", models.CharField(blank=True, max_length=20)),
                ("classificacao_original", models.CharField(blank=True, max_length=20)),
                ("classificacao_nova", models.CharField(blank=True, max_length=20)),
                ("descricao_original", models.CharField(blank=True, max_length=500)),
                ("descricao_nova", models.CharField(blank=True, max_length=500)),
                ("dismiss", models.BooleanField(default=False)),
                ("rotate_degrees", models.IntegerField(blank=True, null=True)),
                ("ia_reprocessamento", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=True)),
                ("mensagem_erro", models.TextField(blank=True)),
                (
                    "entrada_financeira",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.entradafinanceira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Correção",
                "verbose_name_plural": "Históricos de Correções",
                "ordering": ["-execution"],
            },
        ),
    ]
