# docker-compose.yml

services:
  cloud-api:
    build:
      context: ./cloud/api
      dockerfile: Dockerfile
    image: ${CLOUD_API_IMAGE:-wa-fin-ctrl-api}
    environment:
      PORT: ${PORT:-3333}
      NODE_ENV: ${NODE_ENV:-production}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3333}
      MESSAGE_PREFIX: ${MESSAGE_PREFIX:-MSG-}
      SUCCESS_MESSAGE: ${SUCCESS_MESSAGE:-Notification registered successfully}
      FILE_HISTORY_METADATA_FILE_NAME: ${FILE_HISTORY_METADATA_FILE_NAME:-file-history-metadata.json}
      FILE_HISTORY_STORAGE_DIR: ${FILE_HISTORY_STORAGE_DIR:-/app/storage/file-history}
      FILE_HISTORY_UPLOADS_DIR: ${FILE_HISTORY_UPLOADS_DIR:-/app/storage/uploads}
      FILE_HISTORY_CACHE_TTL: ${FILE_HISTORY_CACHE_TTL:-60000}
      FILE_HISTORY_DEFAULT_PAGE_SIZE: ${FILE_HISTORY_DEFAULT_PAGE_SIZE:-10}
      FILE_HISTORY_MAX_PAGE_SIZE: ${FILE_HISTORY_MAX_PAGE_SIZE:-100}
      UPLOAD_METADATA_STORAGE_DIR: ${UPLOAD_METADATA_STORAGE_DIR:-/app/storage/metadata}
      FILES_PUBLIC_URL: ${FILES_PUBLIC_URL:-http://localhost:3333/uploads}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      OPENROUTER_BASE_URL: ${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1/chat/completions}
      OPENROUTER_PDF_MODEL: ${OPENROUTER_PDF_MODEL:-anthropic/claude-sonnet-4}
      OPENROUTER_PDF_ENGINE: ${OPENROUTER_PDF_ENGINE:-mistral-ocr}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_SERVICE_DISABLED_MESSAGE: ${OPENAI_SERVICE_DISABLED_MESSAGE:-OpenAI integration disabled in this environment}
      OPENAI_RATE_LIMIT: ${OPENAI_RATE_LIMIT:-1r/m}
      AUTHORIZED_DOMAINS: ${AUTHORIZED_DOMAINS:-}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN:-}
      GOOGLE_DRIVE_FOLDER_ID: ${GOOGLE_DRIVE_FOLDER_ID:-}
      NGINX_PORT: ${NGINX_PORT:-8080}
      NGINX_RATE_LIMIT_LLM: ${NGINX_RATE_LIMIT_LLM:-1r/m}
      NGINX_BURST_LLM: ${NGINX_BURST_LLM:-5}
      NGINX_RATE_LIMIT_GENERAL: ${NGINX_RATE_LIMIT_GENERAL:-10r/m}
      NGINX_BURST_GENERAL: ${NGINX_BURST_GENERAL:-20}
      DIAGNOSTICS_API_INTERNAL_PORT: ${DIAGNOSTICS_API_INTERNAL_PORT:-3334}
      JWT_SECRET_MOCK: ${JWT_SECRET_MOCK:-mock-jwt-secret}
      TOKEN_EXPIRATION_SECONDS: ${TOKEN_EXPIRATION_SECONDS:-3600}
      DEMO_USER_EMAIL: ${DEMO_USER_EMAIL:-demo@example.com}
      DEMO_USER_NAME: ${DEMO_USER_NAME:-Demo User}
      DEMO_USER_PICTURE: ${DEMO_USER_PICTURE:-https://via.placeholder.com/40}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL:-admin@example.com}
      ADMIN_USER_NAME: ${ADMIN_USER_NAME:-Admin User}
      ADMIN_USER_PICTURE: ${ADMIN_USER_PICTURE:-https://via.placeholder.com/40}
      TEST_USER_EMAIL: ${TEST_USER_EMAIL:-test@example.com}
      TEST_USER_NAME: ${TEST_USER_NAME:-Test User}
      TEST_USER_PICTURE: ${TEST_USER_PICTURE:-https://via.placeholder.com/40}
    ports:
      - "${CLOUD_API_PORT:-3333}:3333"
    volumes:
      - ./cloud/api/extracted:/app/extracted

  cloud-ui:
    build:
      context: ./cloud/ui
      dockerfile: Dockerfile
    image: ${CLOUD_UI_IMAGE:-wa-fin-ctrl-ui}
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3333}
    depends_on:
      - cloud-api
    ports:
      - "${CLOUD_UI_PORT:-8080}:80"
