services:
  app:
    build:
      context: .
    image: wa-fin-ctrl-app:latest
    container_name: wa-fin-ctrl-app
    command: ["poetry", "run", "uvicorn", "src.wa_fin_ctrl.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./wa-fin.py:/app/wa-fin.py
      - ./Makefile:/app/Makefile
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./db:/app/db
      - ./docs:/app/docs
      - ./imgs:/app/imgs
      - ./input:/app/input
      - ./massa:/app/massa
      - ./mensagens:/app/mensagens
      - ./ocr:/app/ocr
      - ./static:/app/static
      - ./templates:/app/templates
      - ./tmp:/app/tmp
    environment:
      PYTHONPATH: /app
    restart: unless-stopped
