[tool.poetry]
name = "gastos-tia-claudia"
version = "0.1.0"
description = ""
authors = ["Malnati <ricardomalnati@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.13"
pandas = ">=2.2.3,<3.0.0"
pillow = ">=11.2.1,<12.0.0"
pytesseract = ">=0.3.13,<0.4.0"
opencv-python = ">=4.11.0.86,<5.0.0.0"
openai = ">=1.82.0,<2.0.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
